INSERT INTO "products" (name, description, price, quantity_in_stock, image_url, category_id, created_at, updated_at) VALUES
('T-Shirt', 'Comfortable cotton t-shirt', 19.99, 100, 'http://example.com/tshirt.jpg', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jeans', 'Stylish blue jeans', 49.99, 50, 'http://example.com/jeans.jpg', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jacket', 'Warm winter jacket', 89.99, 30, 'http://example.com/jacket.jpg', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sweater', 'Cozy wool sweater', 39.99, 40, 'http://example.com/sweater.jpg', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shorts', 'Casual summer shorts', 24.99, 60, 'http://example.com/shorts.jpg', 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Dress', 'Elegant evening dress', 79.99, 20, 'http://example.com/dress.jpg', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Skirt', 'Chic mini skirt', 29.99, 70, 'http://example.com/skirt.jpg', 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blouse', 'Silk blouse', 34.99, 50, 'http://example.com/blouse.jpg', 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coat', 'Long trench coat', 99.99, 15, 'http://example.com/coat.jpg', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Socks', 'Warm wool socks', 9.99, 200, 'http://example.com/socks.jpg', 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hat', 'Stylish fedora hat', 19.99, 30, 'http://example.com/hat.jpg', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Scarf', 'Cozy winter scarf', 14.99, 80, 'http://example.com/scarf.jpg', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gloves', 'Leather gloves', 24.99, 40, 'http://example.com/gloves.jpg', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Belt', 'Leather belt', 19.99, 50, 'http://example.com/belt.jpg', 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Shoes', 'Running shoes', 59.99, 30, 'http://example.com/shoes.jpg', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Boots', 'Winter boots', 79.99, 20, 'http://example.com/boots.jpg', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sandals', 'Summer sandals', 29.99, 40, 'http://example.com/sandals.jpg', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Slippers', 'Comfortable slippers', 14.99, 60, 'http://example.com/slippers.jpg', 11, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pajamas', 'Cotton pajamas', 34.99, 30, 'http://example.com/pajamas.jpg', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Underwear', 'Boxer shorts', 9.99, 100, 'http://example.com/underwear.jpg', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bra', 'Lace bra', 19.99, 50, 'http://example.com/bra.jpg', 12, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Swimsuit', 'One-piece swimsuit', 29.99, 20, 'http://example.com/swimsuit.jpg', 13, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tracksuit', 'Comfortable tracksuit', 49.99, 25, 'http://example.com/tracksuit.jpg', 14, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cap', 'Baseball cap', 14.99, 70, 'http://example.com/cap.jpg', 9, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Blazer', 'Formal blazer', 69.99, 15, 'http://example.com/blazer.jpg', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cardigan', 'Knitted cardigan', 39.99, 30, 'http://example.com/cardigan.jpg', 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vest', 'Puffer vest', 49.99, 20, 'http://example.com/vest.jpg', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Leggings', 'Sport leggings', 24.99, 50, 'http://example.com/leggings.jpg', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tights', 'Opaque tights', 12.99, 80, 'http://example.com/tights.jpg', 16, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suit', 'Business suit', 199.99, 10, 'http://example.com/suit.jpg', 15, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);